[world]
kind = "WorldContract"
class_hash = "0x6f4515274ee23404789c3351a77107d0ec07508530119822046600ca6948d6e"
original_class_hash = "0x6f4515274ee23404789c3351a77107d0ec07508530119822046600ca6948d6e"
abi = "manifests/dev/deployment/abis/dojo-world.json"
address = "0x6d5313d73973bb9bbd5c76f5a4d8f5f5f3f244c95596a01391de6a63f77f4b2"
transaction_hash = "0x1a35538cfb064fa8295e3fa8285f987332dcc0d5dd1348ea36638cbe846d7f9"
block_number = 3
seed = "diamond_pit"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "dev"
rpc_url = "https://api.cartridge.gg/x/diamond-pit/katana"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
address = "0x1e3d5078d20dbcd0457d93a9a201e1ba9b58e09a68a4d48b2b3a9894942e1ac"
class_hash = "0x709f306e58038d3350fa368bcb871a16f436bef5fc851537df03b51888959b6"
original_class_hash = "0x709f306e58038d3350fa368bcb871a16f436bef5fc851537df03b51888959b6"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/diamond_pit-actions-3fc18067.json"
reads = []
writes = ["ns:diamond_pit"]
init_calldata = []
tag = "diamond_pit-actions"
systems = [
    "hit_block",
    "sync_position",
    "sell_all",
    "upgrade_pickaxe",
    "upgrade_backpack",
    "set_username",
    "rebirth",
    "open_egg",
    "free_daily_credits",
    "generate_world",
]
manifest_name = "diamond_pit-actions-3fc18067"

[[models]]
kind = "DojoModel"
class_hash = "0x474a925eb4e2613d71d04d491ff3643835c68e142115ea6a3f2321ecd9c350f"
original_class_hash = "0x474a925eb4e2613d71d04d491ff3643835c68e142115ea6a3f2321ecd9c350f"
abi = "manifests/dev/deployment/abis/models/diamond_pit-BlocksColumn-766b200b.json"
tag = "diamond_pit-BlocksColumn"
qualified_path = "diamond_pit::models::blocks_column::blocks_column"
manifest_name = "diamond_pit-BlocksColumn-766b200b"

[[models.members]]
name = "x"
type = "u8"
key = true

[[models.members]]
name = "y"
type = "u8"
key = true

[[models.members]]
name = "z_layer"
type = "u8"
key = true

[[models.members]]
name = "data"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x73fb899e17655effb8f5ab8e389cf2a848d4b1dc2f01345bf94b75e8485d7fd"
original_class_hash = "0x73fb899e17655effb8f5ab8e389cf2a848d4b1dc2f01345bf94b75e8485d7fd"
abi = "manifests/dev/deployment/abis/models/diamond_pit-DailyLeaderboardEntry-1d6ce5ad.json"
tag = "diamond_pit-DailyLeaderboardEntry"
qualified_path = "diamond_pit::models::daily_leaderboard_entry::daily_leaderboard_entry"
manifest_name = "diamond_pit-DailyLeaderboardEntry-1d6ce5ad"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "day"
type = "u32"
key = true

[[models.members]]
name = "nb_coins_collected"
type = "u64"
key = false

[[models.members]]
name = "nb_blocks_broken"
type = "u16"
key = false

[[models.members]]
name = "nb_hits"
type = "u16"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x72a2505ea6a4bc3c6c6773f0fc1144a1d0a5367d6d9cd135d2152446c3988ca"
original_class_hash = "0x72a2505ea6a4bc3c6c6773f0fc1144a1d0a5367d6d9cd135d2152446c3988ca"
abi = "manifests/dev/deployment/abis/models/diamond_pit-PetInventory-6e47b70b.json"
tag = "diamond_pit-PetInventory"
qualified_path = "diamond_pit::models::pet_inventory::pet_inventory"
manifest_name = "diamond_pit-PetInventory-6e47b70b"

[[models.members]]
name = "owner"
type = "ContractAddress"
key = true

[[models.members]]
name = "bunnies"
type = "u32"
key = false

[[models.members]]
name = "birds"
type = "u32"
key = false

[[models.members]]
name = "rams"
type = "u32"
key = false

[[models.members]]
name = "chickens"
type = "u32"
key = false

[[models.members]]
name = "rhinos"
type = "u32"
key = false

[[models.members]]
name = "reptiles"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x4f2c42a85652e649f70de3221600c24a4e68df8a59b98a9e7cf11b2833e3b3d"
original_class_hash = "0x4f2c42a85652e649f70de3221600c24a4e68df8a59b98a9e7cf11b2833e3b3d"
abi = "manifests/dev/deployment/abis/models/diamond_pit-PlayerInventory-676ae3a3.json"
tag = "diamond_pit-PlayerInventory"
qualified_path = "diamond_pit::models::player_inventory::player_inventory"
manifest_name = "diamond_pit-PlayerInventory-676ae3a3"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "data"
type = "u64"
key = false

[[models.members]]
name = "coins"
type = "u64"
key = false

[[models.members]]
name = "rebirth_credits"
type = "u64"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x71e191e88aad0d5eb241e27c375cd532928e055a9e7787abf6bbe61c6c062d"
original_class_hash = "0x71e191e88aad0d5eb241e27c375cd532928e055a9e7787abf6bbe61c6c062d"
abi = "manifests/dev/deployment/abis/models/diamond_pit-PlayerPosition-69b522e7.json"
tag = "diamond_pit-PlayerPosition"
qualified_path = "diamond_pit::models::player_position::player_position"
manifest_name = "diamond_pit-PlayerPosition-69b522e7"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "x"
type = "u32"
key = false

[[models.members]]
name = "y"
type = "u32"
key = false

[[models.members]]
name = "z"
type = "u32"
key = false

[[models.members]]
name = "time"
type = "u64"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x4c8818b4c78587a8d462eb8dd19f633b485d589905b8aaa7bc2ac8b4e829872"
original_class_hash = "0x4c8818b4c78587a8d462eb8dd19f633b485d589905b8aaa7bc2ac8b4e829872"
abi = "manifests/dev/deployment/abis/models/diamond_pit-PlayerStats-20bc78b8.json"
tag = "diamond_pit-PlayerStats"
qualified_path = "diamond_pit::models::player_stats::player_stats"
manifest_name = "diamond_pit-PlayerStats-20bc78b8"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "name"
type = "felt252"
key = false

[[models.members]]
name = "backpack_level"
type = "u8"
key = false

[[models.members]]
name = "pickaxe_level"
type = "u8"
key = false

[[models.members]]
name = "rebirth"
type = "u16"
key = false

[[models.members]]
name = "next_daily_coin"
type = "u64"
key = false
